version: '3.8'

services:
  bitrix-bot:
    build: .
    container_name: labels-generator-bot
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./LabelsMarksGenerator/img:/app/LabelsMarksGenerator/img
      - ./LabelsMarksGenerator/input:/app/LabelsMarksGenerator/input
      - ./LabelsMarksGenerator/output:/app/LabelsMarksGenerator/output
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge